### ISSUE TITLE
move this repository to the CellML organisation

### ISSUE THREAD

**Issue by nickerso** [PMR2/cellml.site#1]
This is the repository for the cellml.org website. Now that we have a CellML organisation on github we should move it over there. See cellml/libcellml#271 for the initial discussion.

**Comment by nickerso** [comment]
Should we just transfer the ownership for this repository or do we make a fork under the CellML organisation?

**Comment by metatoaster** [comment]
Transfer should be fine.

**Comment by nickerso** [comment]
Transferred to the CellML organisation and hopefully given everyone access who needs it.
